replicaCount: 1

image:
  repository: kiplayo/health-monitoring
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 8080
resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
  path: /metrics

grafana:
  dashboards:
    enabled: true
prometheus:
  rules:
    enabled: true
  # labels: {}
  # # Specify the annotations to add to the ServiceMonitor
  # annotations: {}
